### ISSUE TITLE
No support for ActiveResource by Rails 4 and later

### ISSUE THREAD

**Issue by chi6rag** [turingschool/curriculum#1046]
This is in reference to the JumpstartLab Curriculum issue regarding no support for ActiveResource by Rails.

Please refer to the following link:-
http://tutorials.jumpstartlab.com/topics/web_services/active_resource.html

The tutorial uses the Rails ActiveResource Library for consuming web APIs. Sadly, it is no longer supported and no alternate tutorial has been published yet. It would be great if the tutorial could be published.

**Comment by JoshCheek** [comment]
Hmm, these days, we usually have students build their own clients. Personally, I prefer this, because even if there is a tool to make it easy, I think it's important that they understand what the tool is building on.

Looking at the interface in our tutorial, I'm not very optimistic about it, because it would likely leak http calls (imagine n+1 query issues, but across your services). Another issue it would have (again, based only on looking at the interface in our tutorial) is knowing what attributes it has. ActiveRecord can do this because they connect to the database and look at the table. You could get the lib to do this with something similar (hit an endpoint that informs your ActiveModel of the schema), but you'd have to build all these abstractions yourself, unless someone has made a gem for them. But even then, how would the gem know without checking the db schema? And while it could do this without too much difficulty, I'd be pretty apprehensive about letting my db schema leak out through my API. Could see myself making a migration and I breaking an app I didn't even know about. An alternative to that would be an `OpenStruct` style object, where it just assumes it has whatever keys you give it. But my experience leads me to be wary of such objects as they blow up somewhere off in the codebase, far away from the source of the issue.

I've worked on a team that implemented our own version of `ActiveResource`, and in the end, I felt it was probably a mistake. An approach that I try these days (though haven't tried it at the scale of that last app) is to separate the data structure from the query. So using the examples in our tutorial, that would be a class like `Person` which was barely more than a few `attr_accessor`s. This requires you to  separate the painful dependency (http requests and mapping local objects to remote resources) from the simple light one you actually need in your code (the user itself). It'll feel strange at first, and I don't have a great pattern for pulling it off, but the design benefits are significant, thus it will accommodate new requirements, be more testable, and easier to understand. My hypothesis is that the reason it is abandoned is because of issues like these.

So, what are your options? Well, the one that I think most people do (or at least, what I do) is build their own client. You have to know a few things, but nothing too crazy. We almost certainly have [lesson plans](https://github.com/turingschool/lesson_plans) and [curriculum](https://github.com/JumpstartLab/curriculum) around it. I could probably give better advice than that, but there's a lot of context that would dictate how I'd approach it, so don't feel comfortable giving any hard advice on it.

It's also possible that other people want this and have created a replacement. Some thoughtful googling might turn it up, or there might be a category on http://ruby-toolbox.com/

The other side of this is actually pretty popular, which is to say that the people excited about SOA and making gems to present APIs (eg [grape](https://github.com/intridea/grape) and [roar](https://github.com/apotonick/roar)) are going to have to consume those APIs. So, what are they doing? That's probably a good place for information, because they're going to be up on the latest tools and have the experience to provide more thoughtful information.

Hope that helps.

**Comment by JoshCheek** [comment]
Oh, one other thought: Check for a protocol to communicate this kind of information. e.g. Hypermedia was really big a while back. I never felt like I really got it, but maybe something like that led to an agreed upon way for an api to communicate this info, and at that point, someone would likely have written a generic lib to consume it, giving you essentially the same ease as `ActiveResource` (though, that does assume you're controlling the API, or that the API follows the protocol).
